### ISSUE TITLE
Poggit Lint

### ISSUE THREAD

**Issue by ghost** [FRashkar-pm/SellUICobblestoneTest#1]
For fix this:

```php

EconomyAPI::getInstance()->addMoney($player, $total);
````

you need get plugin manager first ;)

```php
$server->getPluginManager()->getPlugin("name");
```

and you can use virion LibEco if you want: 

```yml
https://github.com/David-pm-pl/libEco
```

**Comment by FRashkar-pm** [comment]
Okay sir, Thankyou very much! ^^

**Comment by FRashkar-pm** [comment]
I have tried it so much, but still get problem 😢
But the plugin works fine, thanks for your information sir 😄

**Comment by ghost** [comment]
you're welcome :)

**Comment by ghost** [comment]
> I have tried it so much, but still get problem 😢 But the plugin works fine, thanks for your information sir 😄

I will try create a pull request fixing the bug

**Comment by FRashkar-pm** [comment]
> > I have tried it so much, but still get problem 😢 But the plugin works fine, thanks for your information sir 😄
> 
> I will try create a pull request fixing the bug

Ok sir, 
I'm still learning too, probably still a lot of experimenting with this plugin

**Comment by ghost** [comment]
you are good, i will create the fork to fix now!
